/* Аджибус — сквозной реестр лексики уровня 2 (уроки 1–30).
   Одна строка на единицу: где введена, какого веса, где возвращается, когда
   активируется посев, что переносится на уроки 31–50.
   Это источник правды по повторяемости: расписание возвратов в program.js
   (поля back у карточек, src у заданий recall, scene.must у урока) собрано отсюда.
   tier: A — двигатель уровня (цель 6 встреч), B — рабочая лексика (4), C — тематическая и посевы (2–3).
   nat — встречи, которые были в материалах и до ревизии; back — назначенные.
*/
window.AJ = window.AJ || {};
window.AJ.ledger = [
  {
    id: 'u001',
    ar: 'السلام عليكم',
    tr: 'ас-саля́му ‘алейку́м',
    ru: 'здравствуйте (букв. «мир вам»)',
    kind: 'core',
    tier: 'A',
    intro: 1,
    theme: 'Новый ученик',
    act: null,
    nat: [2, 5],
    back: [4, 8, 14],
    next: [],
    enc: 6
  },
  {
    id: 'u002',
    ar: 'وعليكم السلام',
    tr: 'уа ‘алейку́му с-саля́м',
    ru: 'и вам мир (ответ на приветствие)',
    kind: 'core',
    tier: 'A',
    intro: 1,
    theme: 'Новый ученик',
    act: null,
    nat: [],
    back: [2, 4, 8, 14, 25],
    next: [],
    enc: 6
  },
  {
    id: 'u003',
    ar: 'أنا…',
    tr: 'а́на…',
    ru: 'я…',
    kind: 'core',
    tier: 'A',
    intro: 1,
    theme: 'Новый ученик',
    act: null,
    nat: [2, 18, 19, 20, 24, 25],
    back: [],
    next: [],
    enc: 7
  },
  {
    id: 'u004',
    ar: 'وأنت؟',
    tr: 'уа а́нта?',
    ru: 'а ты?',
    kind: 'core',
    tier: 'A',
    intro: 1,
    theme: 'Новый ученик',
    act: null,
    nat: [9, 18],
    back: [2, 4, 8],
    next: [],
    enc: 6
  },
  {
    id: 'u005',
    ar: 'مع السلامة',
    tr: 'ма‘а с-саля́ма',
    ru: 'до свидания',
    kind: 'core',
    tier: 'A',
    intro: 1,
    theme: 'Новый ученик',
    act: null,
    nat: [2],
    back: [4, 8, 14, 25],
    next: [],
    enc: 6
  },
  {
    id: 'u006',
    ar: 'أهلاً وسهلاً',
    tr: 'а́хлян уа са́хлян',
    ru: 'добро пожаловать',
    kind: 'seed',
    tier: 'C',
    intro: 1,
    theme: 'Новый ученик',
    act: 10,
    nat: [],
    back: [10],
    next: [],
    enc: 2
  },
  {
    id: 'u007',
    ar: 'تفضّل',
    tr: 'тафа́ддаль',
    ru: 'прошу, проходи',
    kind: 'seed',
    tier: 'A',
    intro: 1,
    theme: 'Новый ученик',
    act: 3,
    nat: [3, 10, 13],
    back: [],
    next: [],
    enc: 4
  },
  {
    id: 'u008',
    ar: 'عجيب',
    tr: '‘аджи́б',
    ru: 'удивительно!',
    kind: 'seed',
    tier: 'C',
    intro: 1,
    theme: 'Новый ученик',
    act: 9,
    nat: [],
    back: [9, 9],
    next: [],
    enc: 2
  },
  {
    id: 'u009',
    ar: 'لا',
    tr: 'ля',
    ru: 'нет',
    kind: 'seed',
    tier: 'A',
    intro: 1,
    theme: 'Новый ученик',
    act: 2,
    nat: [2, 3, 5, 6, 7, 8, 12, 13, 14, 15, 16, 17, 19, 20, 22, 23, 24, 26, 27, 28, 29],
    back: [],
    next: [],
    enc: 22
  },
  {
    id: 'u010',
    ar: 'ما هذا؟',
    tr: 'ма ха́за?',
    ru: 'что это?',
    kind: 'core',
    tier: 'A',
    intro: 2,
    theme: 'Что это?',
    act: null,
    nat: [3, 5, 7],
    back: [9, 15],
    next: [],
    enc: 6
  },
  {
    id: 'u011',
    ar: 'هذا…',
    tr: 'ха́за…',
    ru: 'это…',
    kind: 'core',
    tier: 'A',
    intro: 2,
    theme: 'Что это?',
    act: null,
    nat: [3, 4, 5, 7, 8, 9, 23],
    back: [],
    next: [],
    enc: 8
  },
  {
    id: 'u012',
    ar: 'نعم',
    tr: 'на́‘ам',
    ru: 'да',
    kind: 'core',
    tier: 'A',
    intro: 2,
    theme: 'Что это?',
    act: null,
    nat: [26],
    back: [3, 5, 9, 15],
    next: [],
    enc: 6
  },
  {
    id: 'u013',
    ar: 'كتاب',
    tr: 'кита́б',
    ru: 'книга',
    kind: 'core',
    tier: 'B',
    intro: 2,
    theme: 'Что это?',
    act: null,
    nat: [3, 21, 23],
    back: [],
    next: [],
    enc: 4
  },
  {
    id: 'u014',
    ar: 'قلم',
    tr: 'ка́лям',
    ru: 'ручка',
    kind: 'core',
    tier: 'C',
    intro: 2,
    theme: 'Что это?',
    act: null,
    nat: [],
    back: [6, 13],
    next: [],
    enc: 3
  },
  {
    id: 'u015',
    ar: 'مفتاح',
    tr: 'мифта́х',
    ru: 'ключ',
    kind: 'core',
    tier: 'B',
    intro: 2,
    theme: 'Что это?',
    act: null,
    nat: [4, 5, 23],
    back: [],
    next: [],
    enc: 4
  },
  {
    id: 'u016',
    ar: 'قطّ',
    tr: 'китт',
    ru: 'кот',
    kind: 'core',
    tier: 'C',
    intro: 2,
    theme: 'Что это?',
    act: null,
    nat: [],
    back: [6, 13],
    next: [],
    enc: 3
  },
  {
    id: 'u017',
    ar: 'كيف حالك؟',
    tr: 'ка́йфа ха́люк?',
    ru: 'как дела?',
    kind: 'seed',
    tier: 'A',
    intro: 2,
    theme: 'Что это?',
    act: 3,
    nat: [9],
    back: [],
    next: [],
    enc: 2
  },
  {
    id: 'u018',
    ar: 'الحمد لله',
    tr: 'альхамдули-лля́х',
    ru: 'слава Богу (в ответ — «хорошо»)',
    kind: 'seed',
    tier: 'A',
    intro: 2,
    theme: 'Что это?',
    act: 4,
    nat: [],
    back: [4],
    next: [],
    enc: 2
  },
  {
    id: 'u019',
    ar: 'أو',
    tr: 'ау',
    ru: 'или',
    kind: 'seed',
    tier: 'C',
    intro: 2,
    theme: 'Что это?',
    act: 6,
    nat: [],
    back: [6],
    next: [],
    enc: 2
  },
  {
    id: 'u020',
    ar: 'أريد…',
    tr: 'ури́ду…',
    ru: 'я хочу…',
    kind: 'core',
    tier: 'A',
    intro: 3,
    theme: 'Чай у Аджибуса',
    act: null,
    nat: [4, 5, 7, 12, 16, 17, 19],
    back: [],
    next: [],
    enc: 8
  },
  {
    id: 'u021',
    ar: 'شكرًا',
    tr: 'шу́кран',
    ru: 'спасибо',
    kind: 'core',
    tier: 'A',
    intro: 3,
    theme: 'Чай у Аджибуса',
    act: null,
    nat: [4, 5],
    back: [6, 10, 17],
    next: [],
    enc: 6
  },
  {
    id: 'u022',
    ar: 'شاي',
    tr: 'шай',
    ru: 'чай',
    kind: 'core',
    tier: 'B',
    intro: 3,
    theme: 'Чай у Аджибуса',
    act: null,
    nat: [4, 7, 8, 12, 16, 26, 30],
    back: [],
    next: [],
    enc: 8
  },
  {
    id: 'u023',
    ar: 'ماء',
    tr: 'ма‑а',
    ru: 'вода',
    kind: 'core',
    tier: 'B',
    intro: 3,
    theme: 'Чай у Аджибуса',
    act: null,
    nat: [17, 22],
    back: [5],
    next: [],
    enc: 4
  },
  {
    id: 'u024',
    ar: 'تمر',
    tr: 'тамр',
    ru: 'финики',
    kind: 'core',
    tier: 'C',
    intro: 3,
    theme: 'Чай у Аджибуса',
    act: null,
    nat: [5],
    back: [7],
    next: [],
    enc: 3
  },
  {
    id: 'u025',
    ar: 'قهوة',
    tr: 'ка́хва',
    ru: 'кофе',
    kind: 'core',
    tier: 'C',
    intro: 3,
    theme: 'Чай у Аджибуса',
    act: null,
    nat: [7, 16, 26],
    back: [],
    next: [],
    enc: 4
  },
  {
    id: 'u026',
    ar: 'لذيذ',
    tr: 'ляз́из',
    ru: 'вкусно',
    kind: 'core',
    tier: 'C',
    intro: 3,
    theme: 'Чай у Аджибуса',
    act: null,
    nat: [],
    back: [7, 15],
    next: [],
    enc: 3
  },
  {
    id: 'u027',
    ar: 'طيّب',
    tr: 'та́йиб',
    ru: 'ладно, хорошо',
    kind: 'seed',
    tier: 'C',
    intro: 3,
    theme: 'Чай у Аджибуса',
    act: 7,
    nat: [],
    back: [7],
    next: [],
    enc: 2
  },
  {
    id: 'u028',
    ar: 'أين…؟',
    tr: 'а́йна…?',
    ru: 'где…?',
    kind: 'core',
    tier: 'A',
    intro: 4,
    theme: 'Айна мифтах?!',
    act: null,
    nat: [5, 11, 12, 18],
    back: [7],
    next: [],
    enc: 6
  },
  {
    id: 'u029',
    ar: 'هنا',
    tr: 'ху́на',
    ru: 'здесь',
    kind: 'core',
    tier: 'A',
    intro: 4,
    theme: 'Айна мифтах?!',
    act: null,
    nat: [13, 17],
    back: [5, 7, 11],
    next: [],
    enc: 6
  },
  {
    id: 'u030',
    ar: 'هناك',
    tr: 'хуна́к',
    ru: 'там',
    kind: 'core',
    tier: 'A',
    intro: 4,
    theme: 'Айна мифтах?!',
    act: null,
    nat: [],
    back: [5, 7, 11, 18, 28],
    next: [],
    enc: 6
  },
  {
    id: 'u031',
    ar: 'المفتاح',
    tr: 'аль-мифта́х',
    ru: 'тот самый ключ',
    kind: 'core',
    tier: 'B',
    intro: 4,
    theme: 'Айна мифтах?!',
    act: null,
    nat: [5],
    back: [6, 10],
    next: [],
    enc: 4
  },
  {
    id: 'u032',
    ar: 'نظّارة',
    tr: 'назза́ра',
    ru: 'очки',
    kind: 'seed',
    tier: 'C',
    intro: 4,
    theme: 'Айна мифтах?!',
    act: 21,
    nat: [],
    back: [25],
    next: [],
    enc: 2
  },
  {
    id: 'u033',
    ar: 'تفّاح',
    tr: 'туффа́х',
    ru: 'яблоки',
    kind: 'seed',
    tier: 'C',
    intro: 4,
    theme: 'Айна мифтах?!',
    act: 5,
    nat: [5, 6],
    back: [],
    next: [],
    enc: 3
  },
  {
    id: 'u034',
    ar: 'موز',
    tr: 'мауз',
    ru: 'бананы',
    kind: 'seed',
    tier: 'C',
    intro: 4,
    theme: 'Айна мифтах?!',
    act: 5,
    nat: [5],
    back: [],
    next: [],
    enc: 2
  },
  {
    id: 'u035',
    ar: 'بكم؟',
    tr: 'бика́м?',
    ru: 'сколько стоит?',
    kind: 'core',
    tier: 'A',
    intro: 5,
    theme: 'Магазин',
    act: null,
    nat: [6],
    back: [8, 12, 19, 30],
    next: [],
    enc: 6
  },
  {
    id: 'u036',
    ar: 'غالي',
    tr: 'га́ли',
    ru: 'дорого',
    kind: 'core',
    tier: 'B',
    intro: 5,
    theme: 'Магазин',
    act: null,
    nat: [6],
    back: [7, 11],
    next: [],
    enc: 4
  },
  {
    id: 'u037',
    ar: 'رخيص',
    tr: 'рахи́с',
    ru: 'дёшево',
    kind: 'core',
    tier: 'B',
    intro: 5,
    theme: 'Магазин',
    act: null,
    nat: [],
    back: [7, 11, 18],
    next: [],
    enc: 4
  },
  {
    id: 'u038',
    ar: 'كم؟',
    tr: 'кам?',
    ru: 'сколько?',
    kind: 'core',
    tier: 'A',
    intro: 6,
    theme: 'Сколько их?',
    act: null,
    nat: [14, 15, 20, 27],
    back: [7],
    next: [],
    enc: 6
  },
  {
    id: 'u039',
    ar: 'واحد',
    tr: 'ва́хид',
    ru: 'один',
    kind: 'core',
    tier: 'B',
    intro: 6,
    theme: 'Сколько их?',
    act: null,
    nat: [14, 15, 25],
    back: [],
    next: [],
    enc: 4
  },
  {
    id: 'u040',
    ar: 'اثنان',
    tr: 'исна́н',
    ru: 'два',
    kind: 'core',
    tier: 'B',
    intro: 6,
    theme: 'Сколько их?',
    act: null,
    nat: [15],
    back: [8, 12],
    next: [],
    enc: 4
  },
  {
    id: 'u041',
    ar: 'ثلاثة',
    tr: 'саля́са',
    ru: 'три',
    kind: 'core',
    tier: 'B',
    intro: 6,
    theme: 'Сколько их?',
    act: null,
    nat: [14, 15, 27],
    back: [],
    next: [],
    enc: 4
  },
  {
    id: 'u042',
    ar: 'أربعة',
    tr: 'а́рбаʿа',
    ru: 'четыре',
    kind: 'core',
    tier: 'B',
    intro: 6,
    theme: 'Сколько их?',
    act: null,
    nat: [],
    back: [8, 12, 20],
    next: [],
    enc: 4
  },
  {
    id: 'u043',
    ar: 'خمسة',
    tr: 'ха́мса',
    ru: 'пять',
    kind: 'core',
    tier: 'B',
    intro: 6,
    theme: 'Сколько их?',
    act: null,
    nat: [14],
    back: [8, 12],
    next: [],
    enc: 4
  },
  {
    id: 'u044',
    ar: 'عشرة',
    tr: 'ʿа́шара',
    ru: 'десять',
    kind: 'core',
    tier: 'B',
    intro: 6,
    theme: 'Сколько их?',
    act: null,
    nat: [14],
    back: [8, 12],
    next: [],
    enc: 4
  },
  {
    id: 'u045',
    ar: 'ستة',
    tr: 'си́тта',
    ru: 'шесть',
    kind: 'seed',
    tier: 'C',
    intro: 6,
    theme: 'Сколько их?',
    act: 14,
    nat: [],
    back: [15],
    next: [],
    enc: 2
  },
  {
    id: 'u046',
    ar: 'سبعة',
    tr: 'са́бʿа',
    ru: 'семь',
    kind: 'seed',
    tier: 'C',
    intro: 6,
    theme: 'Сколько их?',
    act: 14,
    nat: [],
    back: [15],
    next: [],
    enc: 2
  },
  {
    id: 'u047',
    ar: 'ثمانية',
    tr: 'сама́ния',
    ru: 'восемь',
    kind: 'seed',
    tier: 'C',
    intro: 6,
    theme: 'Сколько их?',
    act: 15,
    nat: [],
    back: [16],
    next: [],
    enc: 2
  },
  {
    id: 'u048',
    ar: 'تسعة',
    tr: 'ти́сʿа',
    ru: 'девять',
    kind: 'seed',
    tier: 'C',
    intro: 6,
    theme: 'Сколько их?',
    act: 15,
    nat: [],
    back: [17],
    next: [],
    enc: 2
  },
  {
    id: 'u049',
    ar: 'لا أريد',
    tr: 'ля ури́ду',
    ru: 'я не хочу',
    kind: 'core',
    tier: 'A',
    intro: 7,
    theme: 'Не хочу — не понимаю',
    act: null,
    nat: [16, 17, 19],
    back: [8, 10],
    next: [],
    enc: 6
  },
  {
    id: 'u050',
    ar: 'لا أفهم',
    tr: 'ля а́фхам',
    ru: 'я не понимаю',
    kind: 'core',
    tier: 'A',
    intro: 7,
    theme: 'Не хочу — не понимаю',
    act: null,
    nat: [8, 19, 29],
    back: [10, 14],
    next: [],
    enc: 6
  },
  {
    id: 'u051',
    ar: 'لا أعرف',
    tr: 'ля а́ʿриф',
    ru: 'я не знаю',
    kind: 'core',
    tier: 'B',
    intro: 7,
    theme: 'Не хочу — не понимаю',
    act: null,
    nat: [],
    back: [9, 13, 21],
    next: [],
    enc: 4
  },
  {
    id: 'u052',
    ar: 'مرة ثانية',
    tr: 'ма́рра са́ния',
    ru: 'ещё раз',
    kind: 'core',
    tier: 'A',
    intro: 7,
    theme: 'Не хочу — не понимаю',
    act: null,
    nat: [8],
    back: [10, 14, 22],
    next: [34],
    enc: 5
  },
  {
    id: 'u053',
    ar: 'ببطء',
    tr: 'би-бутʼ',
    ru: 'помедленнее',
    kind: 'seed',
    tier: 'A',
    intro: 7,
    theme: 'Не хочу — не понимаю',
    act: 12,
    nat: [],
    back: [12],
    next: [],
    enc: 2
  },
  {
    id: 'u054',
    ar: 'ما معنى...؟',
    tr: 'ма ма́ʿна...?',
    ru: 'что значит...?',
    kind: 'seed',
    tier: 'C',
    intro: 7,
    theme: 'Не хочу — не понимаю',
    act: 17,
    nat: [],
    back: [19],
    next: [],
    enc: 2
  },
  {
    id: 'u055',
    ar: 'من فضلك',
    tr: 'мин фа́длик',
    ru: 'пожалуйста (просьба)',
    kind: 'seed',
    tier: 'A',
    intro: 7,
    theme: 'Не хочу — не понимаю',
    act: 16,
    nat: [13, 16, 17, 28],
    back: [],
    next: [],
    enc: 5
  },
  {
    id: 'u056',
    ar: 'عندي',
    tr: 'ʿи́нди',
    ru: 'у меня есть',
    kind: 'core',
    tier: 'A',
    intro: 8,
    theme: 'У меня есть',
    act: null,
    nat: [9, 10, 19, 23, 24, 25],
    back: [],
    next: [],
    enc: 7
  },
  {
    id: 'u057',
    ar: 'عندك',
    tr: 'ʿи́ндак',
    ru: 'у тебя есть',
    kind: 'core',
    tier: 'A',
    intro: 8,
    theme: 'У меня есть',
    act: null,
    nat: [9, 23],
    back: [11, 16, 23],
    next: [],
    enc: 5
  },
  {
    id: 'u058',
    ar: 'ماذا عندك؟',
    tr: 'ма́за ʿи́ндак?',
    ru: 'что у тебя есть?',
    kind: 'core',
    tier: 'A',
    intro: 8,
    theme: 'У меня есть',
    act: null,
    nat: [9],
    back: [11, 16, 23],
    next: [35],
    enc: 5
  },
  {
    id: 'u059',
    ar: 'وقت',
    tr: 'вакт',
    ru: 'время',
    kind: 'core',
    tier: 'B',
    intro: 8,
    theme: 'У меня есть',
    act: null,
    nat: [10, 19, 26],
    back: [],
    next: [],
    enc: 4
  },
  {
    id: 'u060',
    ar: 'فكرة',
    tr: 'фи́кра',
    ru: 'идея',
    kind: 'core',
    tier: 'B',
    intro: 8,
    theme: 'У меня есть',
    act: null,
    nat: [26],
    back: [10, 15],
    next: [],
    enc: 4
  },
  {
    id: 'u061',
    ar: 'ضيف',
    tr: 'дайф',
    ru: 'гость',
    kind: 'seed',
    tier: 'C',
    intro: 8,
    theme: 'У меня есть',
    act: 10,
    nat: [],
    back: [10],
    next: [],
    enc: 2
  },
  {
    id: 'u062',
    ar: 'مشكلة',
    tr: 'му́шкиля',
    ru: 'проблема',
    kind: 'seed',
    tier: 'C',
    intro: 8,
    theme: 'У меня есть',
    act: 20,
    nat: [],
    back: [23],
    next: [],
    enc: 2
  },
  {
    id: 'u063',
    ar: 'من هذا؟',
    tr: 'ман ха́за?',
    ru: 'кто это? (о мужчине)',
    kind: 'core',
    tier: 'A',
    intro: 9,
    theme: 'Кто это?',
    act: null,
    nat: [23],
    back: [10, 12, 17, 25],
    next: [],
    enc: 6
  },
  {
    id: 'u064',
    ar: 'من هذه؟',
    tr: 'ман ха́зихи?',
    ru: 'кто это? (о женщине)',
    kind: 'core',
    tier: 'A',
    intro: 9,
    theme: 'Кто это?',
    act: null,
    nat: [],
    back: [10, 12, 17, 25],
    next: [37],
    enc: 5
  },
  {
    id: 'u065',
    ar: 'أب',
    tr: 'аб',
    ru: 'отец',
    kind: 'core',
    tier: 'B',
    intro: 9,
    theme: 'Кто это?',
    act: null,
    nat: [16, 17, 21, 23],
    back: [],
    next: [],
    enc: 5
  },
  {
    id: 'u066',
    ar: 'أم',
    tr: 'умм',
    ru: 'мама',
    kind: 'core',
    tier: 'B',
    intro: 9,
    theme: 'Кто это?',
    act: null,
    nat: [13, 14, 15, 24, 25, 27, 28, 29, 30],
    back: [],
    next: [],
    enc: 10
  },
  {
    id: 'u067',
    ar: 'أخ',
    tr: 'ах',
    ru: 'брат',
    kind: 'core',
    tier: 'B',
    intro: 9,
    theme: 'Кто это?',
    act: null,
    nat: [20, 26, 30],
    back: [],
    next: [],
    enc: 4
  },
  {
    id: 'u068',
    ar: 'أخت',
    tr: 'ухт',
    ru: 'сестра',
    kind: 'core',
    tier: 'B',
    intro: 9,
    theme: 'Кто это?',
    act: null,
    nat: [],
    back: [11, 16, 24],
    next: [],
    enc: 4
  },
  {
    id: 'u069',
    ar: 'صديق',
    tr: 'сади́к',
    ru: 'друг',
    kind: 'core',
    tier: 'B',
    intro: 9,
    theme: 'Кто это?',
    act: null,
    nat: [21],
    back: [11, 16],
    next: [],
    enc: 4
  },
  {
    id: 'u070',
    ar: 'صديقة',
    tr: 'сади́ка',
    ru: 'подруга',
    kind: 'core',
    tier: 'B',
    intro: 9,
    theme: 'Кто это?',
    act: null,
    nat: [21],
    back: [12, 16],
    next: [],
    enc: 4
  },
  {
    id: 'u071',
    ar: 'جدة',
    tr: 'джа́дда',
    ru: 'бабушка',
    kind: 'seed',
    tier: 'C',
    intro: 9,
    theme: 'Кто это?',
    act: 25,
    nat: [],
    back: [30],
    next: [],
    enc: 2
  },
  {
    id: 'u072',
    ar: 'تعال',
    tr: 'таʿа́ль',
    ru: 'приходи',
    kind: 'core',
    tier: 'A',
    intro: 10,
    theme: 'Гость',
    act: null,
    nat: [11, 13, 29],
    back: [18, 26],
    next: [],
    enc: 6
  },
  {
    id: 'u073',
    ar: 'متى؟',
    tr: 'ма́та?',
    ru: 'когда?',
    kind: 'core',
    tier: 'A',
    intro: 10,
    theme: 'Гость',
    act: null,
    nat: [11, 18, 25],
    back: [13, 18],
    next: [],
    enc: 5
  },
  {
    id: 'u074',
    ar: 'اليوم',
    tr: 'аль-я́ум',
    ru: 'сегодня',
    kind: 'core',
    tier: 'A',
    intro: 10,
    theme: 'Гость',
    act: null,
    nat: [15, 30],
    back: [11, 13, 18],
    next: [],
    enc: 6
  },
  {
    id: 'u075',
    ar: 'غدًا',
    tr: 'га́дан',
    ru: 'завтра',
    kind: 'core',
    tier: 'A',
    intro: 10,
    theme: 'Гость',
    act: null,
    nat: [15, 27],
    back: [11, 13, 18],
    next: [],
    enc: 6
  },
  {
    id: 'u076',
    ar: 'بيتي',
    tr: 'ба́йти',
    ru: 'мой дом',
    kind: 'core',
    tier: 'B',
    intro: 10,
    theme: 'Гость',
    act: null,
    nat: [21, 23],
    back: [12],
    next: [],
    enc: 4
  },
  {
    id: 'u077',
    ar: 'إن شاء الله',
    tr: 'ин ша́а Лла́х',
    ru: 'если пожелает Аллах',
    kind: 'seed',
    tier: 'A',
    intro: 10,
    theme: 'Гость',
    act: 27,
    nat: [27],
    back: [],
    next: [],
    enc: 2
  },
  {
    id: 'u078',
    ar: 'مع أخي',
    tr: 'ма́ʿа а́хи',
    ru: 'с моим братом',
    kind: 'seed',
    tier: 'C',
    intro: 10,
    theme: 'Гость',
    act: 18,
    nat: [],
    back: [20],
    next: [],
    enc: 2
  },
  {
    id: 'u079',
    ar: 'إلى أين؟',
    tr: 'иля а́йна?',
    ru: 'куда?',
    kind: 'core',
    tier: 'A',
    intro: 11,
    theme: 'Куда?',
    act: null,
    nat: [12],
    back: [14, 19, 27],
    next: [32],
    enc: 5
  },
  {
    id: 'u080',
    ar: 'أذهب إلى',
    tr: 'а́зхаб и́ля',
    ru: 'я иду в',
    kind: 'core',
    tier: 'A',
    intro: 11,
    theme: 'Куда?',
    act: null,
    nat: [12],
    back: [14, 19, 27],
    next: [32],
    enc: 5
  },
  {
    id: 'u081',
    ar: 'السوق',
    tr: 'ас-сук',
    ru: 'рынок',
    kind: 'core',
    tier: 'B',
    intro: 11,
    theme: 'Куда?',
    act: null,
    nat: [12, 30],
    back: [13],
    next: [],
    enc: 4
  },
  {
    id: 'u082',
    ar: 'المسجد',
    tr: 'аль-ма́сджид',
    ru: 'мечеть',
    kind: 'core',
    tier: 'B',
    intro: 11,
    theme: 'Куда?',
    act: null,
    nat: [27],
    back: [13, 19],
    next: [],
    enc: 4
  },
  {
    id: 'u083',
    ar: 'البيت',
    tr: 'аль-байт',
    ru: 'дом',
    kind: 'core',
    tier: 'B',
    intro: 11,
    theme: 'Куда?',
    act: null,
    nat: [13, 15, 30],
    back: [],
    next: [],
    enc: 4
  },
  {
    id: 'u084',
    ar: 'العمل',
    tr: 'аль-ʿа́маль',
    ru: 'работа',
    kind: 'seed',
    tier: 'C',
    intro: 11,
    theme: 'Куда?',
    act: 18,
    nat: [12],
    back: [],
    next: [],
    enc: 2
  },
  {
    id: 'u085',
    ar: 'المقهى',
    tr: 'аль-ма́кха',
    ru: 'кафе',
    kind: 'seed',
    tier: 'C',
    intro: 11,
    theme: 'Куда?',
    act: 27,
    nat: [27],
    back: [],
    next: [],
    enc: 2
  },
  {
    id: 'u086',
    ar: 'أذهب',
    tr: 'а́зхаб',
    ru: 'я иду',
    kind: 'core',
    tier: 'A',
    intro: 12,
    theme: 'Я иду',
    act: null,
    nat: [13],
    back: [16, 21, 28],
    next: [33],
    enc: 5
  },
  {
    id: 'u087',
    ar: 'تذهب',
    tr: 'та́зхаб',
    ru: 'ты идёшь',
    kind: 'core',
    tier: 'A',
    intro: 12,
    theme: 'Я иду',
    act: null,
    nat: [28],
    back: [13, 16, 21, 28],
    next: [],
    enc: 5
  },
  {
    id: 'u088',
    ar: 'يذهب',
    tr: 'я́зхаб',
    ru: 'он идёт',
    kind: 'core',
    tier: 'A',
    intro: 12,
    theme: 'Я иду',
    act: null,
    nat: [13, 28],
    back: [16, 21, 28],
    next: [],
    enc: 5
  },
  {
    id: 'u089',
    ar: 'أعمل',
    tr: 'а́ʿмаль',
    ru: 'я работаю',
    kind: 'core',
    tier: 'B',
    intro: 12,
    theme: 'Я иду',
    act: null,
    nat: [],
    back: [15, 20, 27],
    next: [],
    enc: 4
  },
  {
    id: 'u090',
    ar: 'أشرب',
    tr: 'а́шраб',
    ru: 'я пью',
    kind: 'core',
    tier: 'B',
    intro: 12,
    theme: 'Я иду',
    act: null,
    nat: [],
    back: [15, 20, 27],
    next: [],
    enc: 4
  },
  {
    id: 'u091',
    ar: 'ماذا تفعل؟',
    tr: 'ма́за та́фʿаль?',
    ru: 'что ты делаешь?',
    kind: 'seed',
    tier: 'C',
    intro: 12,
    theme: 'Я иду',
    act: 18,
    nat: [],
    back: [20],
    next: [],
    enc: 2
  },
  {
    id: 'u092',
    ar: 'الآن',
    tr: 'аль-а́н',
    ru: 'сейчас',
    kind: 'seed',
    tier: 'C',
    intro: 12,
    theme: 'Я иду',
    act: 14,
    nat: [],
    back: [15],
    next: [],
    enc: 2
  },
  {
    id: 'u093',
    ar: 'يمين',
    tr: 'ями́н',
    ru: 'направо',
    kind: 'core',
    tier: 'A',
    intro: 13,
    theme: 'Такси',
    act: null,
    nat: [],
    back: [14, 17, 22, 30],
    next: [34],
    enc: 5
  },
  {
    id: 'u094',
    ar: 'يسار',
    tr: 'яса́р',
    ru: 'налево',
    kind: 'core',
    tier: 'A',
    intro: 13,
    theme: 'Такси',
    act: null,
    nat: [],
    back: [14, 17, 22, 30],
    next: [34],
    enc: 5
  },
  {
    id: 'u095',
    ar: 'إلى الأمام',
    tr: 'и́ля ль-ама́м',
    ru: 'прямо, вперёд',
    kind: 'core',
    tier: 'A',
    intro: 13,
    theme: 'Такси',
    act: null,
    nat: [27],
    back: [14, 17, 22, 30],
    next: [],
    enc: 6
  },
  {
    id: 'u096',
    ar: 'قف',
    tr: 'киф',
    ru: 'стоп, остановись',
    kind: 'core',
    tier: 'A',
    intro: 13,
    theme: 'Такси',
    act: null,
    nat: [29],
    back: [15, 17, 22, 30],
    next: [],
    enc: 6
  },
  {
    id: 'u097',
    ar: 'هنا من فضلك',
    tr: 'ху́на мин фа́длик',
    ru: 'здесь, пожалуйста',
    kind: 'core',
    tier: 'B',
    intro: 13,
    theme: 'Такси',
    act: null,
    nat: [],
    back: [16, 21, 29],
    next: [],
    enc: 4
  },
  {
    id: 'u098',
    ar: 'شارع',
    tr: 'ша́риʿ',
    ru: 'улица',
    kind: 'seed',
    tier: 'C',
    intro: 13,
    theme: 'Такси',
    act: 18,
    nat: [],
    back: [20],
    next: [],
    enc: 2
  },
  {
    id: 'u099',
    ar: 'قريب',
    tr: 'кари́б',
    ru: 'близко',
    kind: 'seed',
    tier: 'C',
    intro: 13,
    theme: 'Такси',
    act: 18,
    nat: [],
    back: [20],
    next: [],
    enc: 2
  },
  {
    id: 'u100',
    ar: 'بعيد',
    tr: 'баʿи́д',
    ru: 'далеко',
    kind: 'seed',
    tier: 'C',
    intro: 13,
    theme: 'Такси',
    act: 18,
    nat: [],
    back: [20],
    next: [],
    enc: 2
  },
  {
    id: 'u101',
    ar: 'ثم',
    tr: 'су́мма',
    ru: 'затем, потом',
    kind: 'seed',
    tier: 'C',
    intro: 13,
    theme: 'Такси',
    act: 27,
    nat: [],
    back: [],
    next: [33],
    enc: 1
  },
  {
    id: 'u102',
    ar: 'كم الساعة؟',
    tr: 'кам ас-са́ʿа?',
    ru: 'который час?',
    kind: 'core',
    tier: 'A',
    intro: 14,
    theme: 'Который час?',
    act: null,
    nat: [15, 20, 27],
    back: [18, 23],
    next: [],
    enc: 6
  },
  {
    id: 'u103',
    ar: 'الساعة الخامسة',
    tr: 'ас-са́ʿа ль-ха́миса',
    ru: 'пять часов',
    kind: 'core',
    tier: 'B',
    intro: 14,
    theme: 'Который час?',
    act: null,
    nat: [15, 27],
    back: [17],
    next: [],
    enc: 4
  },
  {
    id: 'u104',
    ar: 'والنصف',
    tr: 'уа-н-нисф',
    ru: 'с половиной',
    kind: 'core',
    tier: 'B',
    intro: 14,
    theme: 'Который час?',
    act: null,
    nat: [],
    back: [18, 22],
    next: [31],
    enc: 3
  },
  {
    id: 'u105',
    ar: 'صباحًا',
    tr: 'саба́хан',
    ru: 'утра',
    kind: 'core',
    tier: 'B',
    intro: 14,
    theme: 'Который час?',
    act: null,
    nat: [],
    back: [18, 23],
    next: [31],
    enc: 3
  },
  {
    id: 'u106',
    ar: 'مساءً',
    tr: 'маса́ʼан',
    ru: 'вечера',
    kind: 'core',
    tier: 'B',
    intro: 14,
    theme: 'Который час?',
    act: null,
    nat: [],
    back: [18, 23],
    next: [31],
    enc: 3
  },
  {
    id: 'u107',
    ar: 'دقيقة',
    tr: 'даки́ка',
    ru: 'минута',
    kind: 'seed',
    tier: 'C',
    intro: 14,
    theme: 'Который час?',
    act: 25,
    nat: [],
    back: [30],
    next: [],
    enc: 2
  },
  {
    id: 'u108',
    ar: 'متأخر',
    tr: 'мутаа́ххир',
    ru: 'опаздывающий, поздно',
    kind: 'seed',
    tier: 'C',
    intro: 14,
    theme: 'Который час?',
    act: 20,
    nat: [20],
    back: [],
    next: [],
    enc: 2
  },
  {
    id: 'u109',
    ar: 'الساعة الثالثة',
    tr: 'ас-са́ʿа с-са́лиса',
    ru: 'три часа',
    kind: 'seed',
    tier: 'C',
    intro: 14,
    theme: 'Который час?',
    act: 15,
    nat: [],
    back: [17],
    next: [],
    enc: 2
  },
  {
    id: 'u110',
    ar: 'الساعة العاشرة',
    tr: 'ас-са́ʿа ль-ʿа́шира',
    ru: 'десять часов',
    kind: 'seed',
    tier: 'C',
    intro: 14,
    theme: 'Который час?',
    act: 27,
    nat: [],
    back: [],
    next: [33],
    enc: 1
  },
  {
    id: 'u111',
    ar: 'يوم',
    tr: 'яум',
    ru: 'день',
    kind: 'core',
    tier: 'B',
    intro: 15,
    theme: 'Дни недели',
    act: null,
    nat: [20, 25, 27, 30],
    back: [],
    next: [],
    enc: 5
  },
  {
    id: 'u112',
    ar: 'الجمعة',
    tr: 'аль-джу́мʿа',
    ru: 'пятница',
    kind: 'core',
    tier: 'B',
    intro: 15,
    theme: 'Дни недели',
    act: null,
    nat: [20, 27],
    back: [19],
    next: [],
    enc: 4
  },
  {
    id: 'u113',
    ar: 'السبت',
    tr: 'ас-сабт',
    ru: 'суббота',
    kind: 'core',
    tier: 'B',
    intro: 15,
    theme: 'Дни недели',
    act: null,
    nat: [27],
    back: [19, 24],
    next: [],
    enc: 4
  },
  {
    id: 'u114',
    ar: 'الأحد',
    tr: 'аль-а́хад',
    ru: 'воскресенье',
    kind: 'core',
    tier: 'B',
    intro: 15,
    theme: 'Дни недели',
    act: null,
    nat: [],
    back: [19, 24],
    next: [32],
    enc: 3
  },
  {
    id: 'u115',
    ar: 'الاثنين',
    tr: 'аль-исна́йн',
    ru: 'понедельник',
    kind: 'core',
    tier: 'B',
    intro: 15,
    theme: 'Дни недели',
    act: null,
    nat: [],
    back: [19, 24],
    next: [32],
    enc: 3
  },
  {
    id: 'u116',
    ar: 'في',
    tr: 'фи',
    ru: 'в (о времени и месте)',
    kind: 'core',
    tier: 'A',
    intro: 15,
    theme: 'Дни недели',
    act: null,
    nat: [16, 18, 20, 25, 27, 30],
    back: [],
    next: [],
    enc: 7
  },
  {
    id: 'u117',
    ar: 'الثلاثاء',
    tr: 'ас-суляса́',
    ru: 'вторник',
    kind: 'seed',
    tier: 'C',
    intro: 15,
    theme: 'Дни недели',
    act: 27,
    nat: [],
    back: [],
    next: [33],
    enc: 1
  },
  {
    id: 'u118',
    ar: 'الأربعاء',
    tr: 'аль-арбиʿа́',
    ru: 'среда',
    kind: 'seed',
    tier: 'C',
    intro: 15,
    theme: 'Дни недели',
    act: 27,
    nat: [],
    back: [],
    next: [33],
    enc: 1
  },
  {
    id: 'u119',
    ar: 'الخميس',
    tr: 'аль-хами́с',
    ru: 'четверг',
    kind: 'seed',
    tier: 'C',
    intro: 15,
    theme: 'Дни недели',
    act: 27,
    nat: [],
    back: [],
    next: [33],
    enc: 1
  },
  {
    id: 'u120',
    ar: 'عصير',
    tr: 'ʿаси́р',
    ru: 'сок',
    kind: 'core',
    tier: 'C',
    intro: 16,
    theme: 'В кафе',
    act: null,
    nat: [],
    back: [23],
    next: [34],
    enc: 2
  },
  {
    id: 'u121',
    ar: 'الحساب',
    tr: 'аль-хиса́б',
    ru: 'счёт',
    kind: 'core',
    tier: 'B',
    intro: 16,
    theme: 'В кафе',
    act: null,
    nat: [17],
    back: [20, 26],
    next: [],
    enc: 4
  },
  {
    id: 'u122',
    ar: 'سكر',
    tr: 'су́ккар',
    ru: 'сахар',
    kind: 'core',
    tier: 'C',
    intro: 16,
    theme: 'В кафе',
    act: null,
    nat: [],
    back: [23],
    next: [34],
    enc: 2
  },
  {
    id: 'u123',
    ar: 'بدون',
    tr: 'биду́н',
    ru: 'без',
    kind: 'core',
    tier: 'C',
    intro: 16,
    theme: 'В кафе',
    act: null,
    nat: [],
    back: [23],
    next: [34],
    enc: 2
  },
  {
    id: 'u124',
    ar: 'حلو',
    tr: 'ху́льв',
    ru: 'сладкий',
    kind: 'seed',
    tier: 'C',
    intro: 16,
    theme: 'В кафе',
    act: 26,
    nat: [],
    back: [],
    next: [31],
    enc: 1
  },
  {
    id: 'u125',
    ar: 'ساخن',
    tr: 'са́хин',
    ru: 'горячий',
    kind: 'seed',
    tier: 'C',
    intro: 16,
    theme: 'В кафе',
    act: 24,
    nat: [30],
    back: [],
    next: [],
    enc: 2
  },
  {
    id: 'u126',
    ar: 'بارد',
    tr: 'ба́рид',
    ru: 'холодный',
    kind: 'seed',
    tier: 'C',
    intro: 16,
    theme: 'В кафе',
    act: 24,
    nat: [],
    back: [28],
    next: [],
    enc: 2
  },
  {
    id: 'u127',
    ar: 'ممكن؟',
    tr: 'му́мкин?',
    ru: 'можно?',
    kind: 'core',
    tier: 'A',
    intro: 17,
    theme: 'Можно?',
    act: null,
    nat: [26],
    back: [19, 22, 27],
    next: [37],
    enc: 5
  },
  {
    id: 'u128',
    ar: 'ممكن ماء؟',
    tr: 'му́мкин ма́ʼ?',
    ru: 'можно воды?',
    kind: 'core',
    tier: 'B',
    intro: 17,
    theme: 'Можно?',
    act: null,
    nat: [],
    back: [21, 26],
    next: [35],
    enc: 3
  },
  {
    id: 'u129',
    ar: 'صورة',
    tr: 'су́ра',
    ru: 'фото, картинка',
    kind: 'core',
    tier: 'C',
    intro: 17,
    theme: 'Можно?',
    act: null,
    nat: [],
    back: [25],
    next: [35],
    enc: 2
  },
  {
    id: 'u130',
    ar: 'طبعًا',
    tr: 'та́бʿан',
    ru: 'конечно',
    kind: 'core',
    tier: 'A',
    intro: 17,
    theme: 'Можно?',
    act: null,
    nat: [24, 26],
    back: [20, 22],
    next: [37],
    enc: 5
  },
  {
    id: 'u131',
    ar: 'للأسف، لا',
    tr: 'лиль-а́саф, ля',
    ru: 'к сожалению, нет',
    kind: 'core',
    tier: 'B',
    intro: 17,
    theme: 'Можно?',
    act: null,
    nat: [22, 26],
    back: [21],
    next: [],
    enc: 4
  },
  {
    id: 'u132',
    ar: 'لحظة',
    tr: 'ла́хза',
    ru: 'секундочку',
    kind: 'seed',
    tier: 'C',
    intro: 17,
    theme: 'Можно?',
    act: 28,
    nat: [28],
    back: [],
    next: [],
    enc: 2
  },
  {
    id: 'u133',
    ar: 'مساعدة',
    tr: 'мусаʿа́да',
    ru: 'помощь',
    kind: 'seed',
    tier: 'C',
    intro: 17,
    theme: 'Можно?',
    act: 19,
    nat: [],
    back: [22],
    next: [],
    enc: 2
  },
  {
    id: 'u134',
    ar: 'أسكن في',
    tr: 'а́скун фи',
    ru: 'я живу в',
    kind: 'core',
    tier: 'A',
    intro: 18,
    theme: 'Где ты живёшь?',
    act: null,
    nat: [],
    back: [21, 21, 24, 28],
    next: [31, 39],
    enc: 4
  },
  {
    id: 'u135',
    ar: 'أين تسكن؟',
    tr: 'а́йна та́скун?',
    ru: 'где ты живёшь?',
    kind: 'core',
    tier: 'B',
    intro: 18,
    theme: 'Где ты живёшь?',
    act: null,
    nat: [],
    back: [23, 28],
    next: [37],
    enc: 3
  },
  {
    id: 'u136',
    ar: 'من أين أنت؟',
    tr: 'мин а́йна а́нта?',
    ru: 'откуда ты?',
    kind: 'core',
    tier: 'A',
    intro: 18,
    theme: 'Где ты живёшь?',
    act: null,
    nat: [],
    back: [21, 21, 24, 28],
    next: [31, 39],
    enc: 4
  },
  {
    id: 'u137',
    ar: 'أنا من',
    tr: 'а́на мин',
    ru: 'я из',
    kind: 'core',
    tier: 'A',
    intro: 18,
    theme: 'Где ты живёшь?',
    act: null,
    nat: [],
    back: [21, 21, 24, 28],
    next: [31, 39],
    enc: 4
  },
  {
    id: 'u138',
    ar: 'مدينة',
    tr: 'мади́на',
    ru: 'город',
    kind: 'core',
    tier: 'B',
    intro: 18,
    theme: 'Где ты живёшь?',
    act: null,
    nat: [21, 26, 30],
    back: [],
    next: [],
    enc: 4
  },
  {
    id: 'u139',
    ar: 'قرية',
    tr: 'ка́рья',
    ru: 'деревня',
    kind: 'seed',
    tier: 'C',
    intro: 18,
    theme: 'Где ты живёшь?',
    act: 22,
    nat: [],
    back: [26],
    next: [],
    enc: 2
  },
  {
    id: 'u140',
    ar: 'حي',
    tr: 'хай',
    ru: 'район',
    kind: 'seed',
    tier: 'C',
    intro: 18,
    theme: 'Где ты живёшь?',
    act: 22,
    nat: [23, 30],
    back: [],
    next: [],
    enc: 3
  },
  {
    id: 'u141',
    ar: 'نقود',
    tr: 'нуку́д',
    ru: 'деньги',
    kind: 'core',
    tier: 'B',
    intro: 19,
    theme: 'Нет денег!',
    act: null,
    nat: [],
    back: [24, 29],
    next: [31],
    enc: 3
  },
  {
    id: 'u142',
    ar: 'ما عندي',
    tr: 'ма ʿи́нди',
    ru: 'у меня нет',
    kind: 'core',
    tier: 'A',
    intro: 19,
    theme: 'Нет денег!',
    act: null,
    nat: [24],
    back: [22, 25],
    next: [32, 31],
    enc: 4
  },
  {
    id: 'u143',
    ar: 'الباقي',
    tr: 'аль-ба́ки',
    ru: 'сдача',
    kind: 'core',
    tier: 'B',
    intro: 19,
    theme: 'Нет денег!',
    act: null,
    nat: [],
    back: [25, 29],
    next: [31],
    enc: 3
  },
  {
    id: 'u144',
    ar: 'أدفع',
    tr: 'а́дфаʿ',
    ru: 'я плачу',
    kind: 'core',
    tier: 'B',
    intro: 19,
    theme: 'Нет денег!',
    act: null,
    nat: [],
    back: [25, 29],
    next: [31],
    enc: 3
  },
  {
    id: 'u145',
    ar: 'بطاقة',
    tr: 'бита́ка',
    ru: 'карта',
    kind: 'seed',
    tier: 'C',
    intro: 19,
    theme: 'Нет денег!',
    act: 25,
    nat: [],
    back: [30],
    next: [],
    enc: 2
  },
  {
    id: 'u146',
    ar: 'مجانًا',
    tr: 'маджа́нан',
    ru: 'бесплатно',
    kind: 'seed',
    tier: 'C',
    intro: 19,
    theme: 'Нет денег!',
    act: 26,
    nat: [],
    back: [],
    next: [31],
    enc: 1
  },
  {
    id: 'u147',
    ar: 'لك',
    tr: 'ля́кя',
    ru: 'тебе',
    kind: 'seed',
    tier: 'C',
    intro: 19,
    theme: 'Нет денег!',
    act: 23,
    nat: [20, 28],
    back: [],
    next: [],
    enc: 3
  },
  {
    id: 'u148',
    ar: 'لماذا؟',
    tr: 'лима́за?',
    ru: 'почему?',
    kind: 'core',
    tier: 'A',
    intro: 20,
    theme: 'Опоздали',
    act: null,
    nat: [27],
    back: [24, 26],
    next: [33, 41],
    enc: 4
  },
  {
    id: 'u149',
    ar: 'لأن',
    tr: 'ли-а́нна',
    ru: 'потому что',
    kind: 'core',
    tier: 'A',
    intro: 20,
    theme: 'Опоздали',
    act: null,
    nat: [22],
    back: [24, 26],
    next: [33, 32],
    enc: 4
  },
  {
    id: 'u150',
    ar: 'الحافلة',
    tr: 'аль-ха́филя',
    ru: 'автобус',
    kind: 'core',
    tier: 'B',
    intro: 20,
    theme: 'Опоздали',
    act: null,
    nat: [],
    back: [26],
    next: [32, 31],
    enc: 2
  },
  {
    id: 'u151',
    ar: 'آسف',
    tr: 'а́сиф',
    ru: 'прости, сожалею',
    kind: 'seed',
    tier: 'A',
    intro: 20,
    theme: 'Опоздали',
    act: 29,
    nat: [22, 26, 28, 29],
    back: [],
    next: [],
    enc: 5
  },
  {
    id: 'u152',
    ar: 'مشغول',
    tr: 'машгу́ль',
    ru: 'занят',
    kind: 'seed',
    tier: 'C',
    intro: 20,
    theme: 'Опоздали',
    act: 28,
    nat: [28],
    back: [],
    next: [],
    enc: 2
  },
  {
    id: 'u153',
    ar: 'كبير',
    tr: 'каби́р',
    ru: 'большой',
    kind: 'core',
    tier: 'A',
    intro: 21,
    theme: 'Какой он?',
    act: null,
    nat: [22, 30],
    back: [27],
    next: [34],
    enc: 4
  },
  {
    id: 'u154',
    ar: 'صغير',
    tr: 'саги́р',
    ru: 'маленький',
    kind: 'core',
    tier: 'A',
    intro: 21,
    theme: 'Какой он?',
    act: null,
    nat: [30],
    back: [25, 27],
    next: [34],
    enc: 4
  },
  {
    id: 'u155',
    ar: 'جديد',
    tr: 'джади́д',
    ru: 'новый',
    kind: 'core',
    tier: 'B',
    intro: 21,
    theme: 'Какой он?',
    act: null,
    nat: [],
    back: [27],
    next: [33, 32],
    enc: 2
  },
  {
    id: 'u156',
    ar: 'قديم',
    tr: 'кади́м',
    ru: 'старый',
    kind: 'core',
    tier: 'B',
    intro: 21,
    theme: 'Какой он?',
    act: null,
    nat: [],
    back: [27],
    next: [33],
    enc: 2
  },
  {
    id: 'u157',
    ar: 'جميل',
    tr: 'джами́ль',
    ru: 'красивый',
    kind: 'core',
    tier: 'A',
    intro: 21,
    theme: 'Какой он?',
    act: null,
    nat: [22],
    back: [27],
    next: [34, 42],
    enc: 3
  },
  {
    id: 'u158',
    ar: 'طويل',
    tr: 'тави́ль',
    ru: 'длинный, высокий',
    kind: 'seed',
    tier: 'C',
    intro: 21,
    theme: 'Какой он?',
    act: 22,
    nat: [],
    back: [26],
    next: [],
    enc: 2
  },
  {
    id: 'u159',
    ar: 'قصير',
    tr: 'касы́р',
    ru: 'короткий, низкий',
    kind: 'seed',
    tier: 'C',
    intro: 21,
    theme: 'Какой он?',
    act: 22,
    nat: [],
    back: [26],
    next: [],
    enc: 2
  },
  {
    id: 'u160',
    ar: 'ما أجمل...!',
    tr: 'ма а́джмаль...!',
    ru: 'как красиво...!',
    kind: 'core',
    tier: 'B',
    intro: 22,
    theme: 'Как красиво!',
    act: null,
    nat: [],
    back: [28],
    next: [34],
    enc: 2
  },
  {
    id: 'u161',
    ar: 'منظر',
    tr: 'ма́нзар',
    ru: 'вид',
    kind: 'core',
    tier: 'C',
    intro: 22,
    theme: 'Как красиво!',
    act: null,
    nat: [],
    back: [],
    next: [33, 32],
    enc: 1
  },
  {
    id: 'u162',
    ar: 'بحر',
    tr: 'бахр',
    ru: 'море',
    kind: 'core',
    tier: 'C',
    intro: 22,
    theme: 'Как красиво!',
    act: null,
    nat: [],
    back: [],
    next: [33, 32],
    enc: 1
  },
  {
    id: 'u163',
    ar: 'سماء',
    tr: 'сама́',
    ru: 'небо',
    kind: 'core',
    tier: 'C',
    intro: 22,
    theme: 'Как красиво!',
    act: null,
    nat: [],
    back: [],
    next: [33, 32],
    enc: 1
  },
  {
    id: 'u164',
    ar: 'ما شاء الله',
    tr: 'ма ша́а Лла́х',
    ru: 'машаллах (восхищение без сглаза)',
    kind: 'core',
    tier: 'A',
    intro: 22,
    theme: 'Как красиво!',
    act: null,
    nat: [24],
    back: [26, 29],
    next: [35],
    enc: 4
  },
  {
    id: 'u165',
    ar: 'نجوم',
    tr: 'нуджу́м',
    ru: 'звёзды',
    kind: 'seed',
    tier: 'C',
    intro: 22,
    theme: 'Как красиво!',
    act: 30,
    nat: [],
    back: [],
    next: [38],
    enc: 1
  },
  {
    id: 'u166',
    ar: 'قمر',
    tr: 'ка́мар',
    ru: 'луна',
    kind: 'seed',
    tier: 'C',
    intro: 22,
    theme: 'Как красиво!',
    act: 30,
    nat: [],
    back: [],
    next: [38],
    enc: 1
  },
  {
    id: 'u167',
    ar: 'كتابي',
    tr: 'кита́би',
    ru: 'моя книга',
    kind: 'core',
    tier: 'B',
    intro: 23,
    theme: 'Мой и твой',
    act: null,
    nat: [],
    back: [29],
    next: [35, 36],
    enc: 2
  },
  {
    id: 'u168',
    ar: 'كتابك',
    tr: 'кита́бук',
    ru: 'твоя книга',
    kind: 'core',
    tier: 'B',
    intro: 23,
    theme: 'Мой и твой',
    act: null,
    nat: [],
    back: [29],
    next: [35, 36],
    enc: 2
  },
  {
    id: 'u169',
    ar: 'كتابه',
    tr: 'кита́бух',
    ru: 'его книга',
    kind: 'core',
    tier: 'B',
    intro: 23,
    theme: 'Мой и твой',
    act: null,
    nat: [],
    back: [29],
    next: [35, 36],
    enc: 2
  },
  {
    id: 'u170',
    ar: 'كتابها',
    tr: 'кита́буха',
    ru: 'её книга',
    kind: 'core',
    tier: 'B',
    intro: 23,
    theme: 'Мой и твой',
    act: null,
    nat: [],
    back: [29],
    next: [35, 36],
    enc: 2
  },
  {
    id: 'u171',
    ar: 'هذا لي',
    tr: 'ха́за ли',
    ru: 'это моё',
    kind: 'core',
    tier: 'B',
    intro: 23,
    theme: 'Мой и твой',
    act: null,
    nat: [],
    back: [29],
    next: [35, 36],
    enc: 2
  },
  {
    id: 'u172',
    ar: 'لمن هذا؟',
    tr: 'ли-ман ха́за?',
    ru: 'чьё это?',
    kind: 'seed',
    tier: 'C',
    intro: 23,
    theme: 'Мой и твой',
    act: 27,
    nat: [],
    back: [],
    next: [34],
    enc: 1
  },
  {
    id: 'u173',
    ar: 'مفتاحي',
    tr: 'мифта́хи',
    ru: 'мой ключ',
    kind: 'seed',
    tier: 'C',
    intro: 23,
    theme: 'Мой и твой',
    act: 25,
    nat: [],
    back: [30],
    next: [],
    enc: 2
  },
  {
    id: 'u174',
    ar: 'رأس',
    tr: 'раʼс',
    ru: 'голова',
    kind: 'core',
    tier: 'C',
    intro: 24,
    theme: 'Что болит?',
    act: null,
    nat: [],
    back: [],
    next: [35],
    enc: 1
  },
  {
    id: 'u175',
    ar: 'بطن',
    tr: 'батн',
    ru: 'живот',
    kind: 'core',
    tier: 'C',
    intro: 24,
    theme: 'Что болит?',
    act: null,
    nat: [],
    back: [],
    next: [35],
    enc: 1
  },
  {
    id: 'u176',
    ar: 'عندي صداع',
    tr: 'ʿи́нди суда́ʿ',
    ru: 'у меня болит голова',
    kind: 'core',
    tier: 'B',
    intro: 24,
    theme: 'Что болит?',
    act: null,
    nat: [25],
    back: [],
    next: [31, 37],
    enc: 2
  },
  {
    id: 'u177',
    ar: 'أنا مريض',
    tr: 'а́на мари́д',
    ru: 'я болен',
    kind: 'core',
    tier: 'B',
    intro: 24,
    theme: 'Что болит?',
    act: null,
    nat: [25],
    back: [],
    next: [31, 37],
    enc: 2
  },
  {
    id: 'u178',
    ar: 'كيف صحتك؟',
    tr: 'ка́йфа сы́ххатук?',
    ru: 'как здоровье?',
    kind: 'core',
    tier: 'B',
    intro: 24,
    theme: 'Что болит?',
    act: null,
    nat: [],
    back: [],
    next: [36, 31, 37],
    enc: 1
  },
  {
    id: 'u179',
    ar: 'دواء',
    tr: 'дава́ʼ',
    ru: 'лекарство',
    kind: 'seed',
    tier: 'C',
    intro: 24,
    theme: 'Что болит?',
    act: 25,
    nat: [],
    back: [30],
    next: [],
    enc: 2
  },
  {
    id: 'u180',
    ar: 'سلامتك',
    tr: 'сала́мтук',
    ru: 'выздоравливай',
    kind: 'seed',
    tier: 'C',
    intro: 24,
    theme: 'Что болит?',
    act: 29,
    nat: [],
    back: [],
    next: [36],
    enc: 1
  },
  {
    id: 'u181',
    ar: 'يوم — أيام',
    tr: 'яум — айя́м',
    ru: 'день — дни',
    kind: 'core',
    tier: 'B',
    intro: 25,
    theme: 'У врача',
    act: null,
    nat: [],
    back: [],
    next: [31, 37, 33],
    enc: 1
  },
  {
    id: 'u182',
    ar: 'أسبوع',
    tr: 'усбу́ʿ',
    ru: 'неделя',
    kind: 'core',
    tier: 'B',
    intro: 25,
    theme: 'У врача',
    act: null,
    nat: [],
    back: [],
    next: [31, 37, 33],
    enc: 1
  },
  {
    id: 'u183',
    ar: 'منذ',
    tr: 'му́нзу',
    ru: 'с, уже (о времени)',
    kind: 'core',
    tier: 'B',
    intro: 25,
    theme: 'У врача',
    act: null,
    nat: [],
    back: [],
    next: [31, 37, 33],
    enc: 1
  },
  {
    id: 'u184',
    ar: 'يومين',
    tr: 'яуме́йн',
    ru: 'два дня',
    kind: 'core',
    tier: 'B',
    intro: 25,
    theme: 'У врача',
    act: null,
    nat: [],
    back: [],
    next: [31, 37, 33],
    enc: 1
  },
  {
    id: 'u185',
    ar: 'حبة',
    tr: 'ха́бба',
    ru: 'таблетка',
    kind: 'seed',
    tier: 'C',
    intro: 25,
    theme: 'У врача',
    act: 31,
    nat: [],
    back: [],
    next: [31],
    enc: 1
  },
  {
    id: 'u186',
    ar: 'كل يوم',
    tr: 'ку́лля яум',
    ru: 'каждый день',
    kind: 'seed',
    tier: 'C',
    intro: 25,
    theme: 'У врача',
    act: 26,
    nat: [],
    back: [],
    next: [32],
    enc: 1
  },
  {
    id: 'u187',
    ar: 'تحب...؟',
    tr: 'тухи́бб...?',
    ru: 'хочешь...? (буквально: любишь?)',
    kind: 'core',
    tier: 'A',
    intro: 26,
    theme: 'Приглашаю',
    act: null,
    nat: [],
    back: [],
    next: [33, 39, 47, 32, 35],
    enc: 1
  },
  {
    id: 'u188',
    ar: 'أحب',
    tr: 'ухи́бб',
    ru: 'я люблю, мне нравится',
    kind: 'core',
    tier: 'A',
    intro: 26,
    theme: 'Приглашаю',
    act: null,
    nat: [],
    back: [],
    next: [33, 39, 47, 32, 35],
    enc: 1
  },
  {
    id: 'u189',
    ar: 'فكرة ممتازة',
    tr: 'фи́кра мумта́за',
    ru: 'отличная идея',
    kind: 'core',
    tier: 'B',
    intro: 26,
    theme: 'Приглашаю',
    act: null,
    nat: [],
    back: [],
    next: [32, 38, 35],
    enc: 1
  },
  {
    id: 'u190',
    ar: 'ممتاز',
    tr: 'мумта́з',
    ru: 'отлично',
    kind: 'core',
    tier: 'B',
    intro: 26,
    theme: 'Приглашаю',
    act: null,
    nat: [],
    back: [],
    next: [32, 38, 35],
    enc: 1
  },
  {
    id: 'u191',
    ar: 'ربما',
    tr: 'ру́ббама',
    ru: 'возможно',
    kind: 'seed',
    tier: 'C',
    intro: 26,
    theme: 'Приглашаю',
    act: 29,
    nat: [27],
    back: [],
    next: [],
    enc: 2
  },
  {
    id: 'u192',
    ar: 'وقت آخر',
    tr: 'вакт а́хар',
    ru: 'в другой раз',
    kind: 'seed',
    tier: 'C',
    intro: 26,
    theme: 'Приглашаю',
    act: 29,
    nat: [],
    back: [],
    next: [36],
    enc: 1
  },
  {
    id: 'u193',
    ar: 'موعد',
    tr: 'ма́уʿид',
    ru: 'встреча, договорённость',
    kind: 'core',
    tier: 'B',
    intro: 27,
    theme: 'Договорились',
    act: null,
    nat: [],
    back: [],
    next: [33, 39, 36],
    enc: 1
  },
  {
    id: 'u194',
    ar: 'إذن',
    tr: 'и́зан',
    ru: 'значит, тогда',
    kind: 'core',
    tier: 'B',
    intro: 27,
    theme: 'Договорились',
    act: null,
    nat: [],
    back: [],
    next: [33, 39, 36],
    enc: 1
  },
  {
    id: 'u195',
    ar: 'اتفقنا',
    tr: 'итта́факна',
    ru: 'договорились!',
    kind: 'core',
    tier: 'A',
    intro: 27,
    theme: 'Договорились',
    act: null,
    nat: [],
    back: [],
    next: [34, 40, 48, 37],
    enc: 1
  },
  {
    id: 'u196',
    ar: 'أمام المقهى',
    tr: 'ама́м аль-ма́кха',
    ru: 'у кафе (перед кафе)',
    kind: 'core',
    tier: 'B',
    intro: 27,
    theme: 'Договорились',
    act: null,
    nat: [],
    back: [],
    next: [33, 39, 36],
    enc: 1
  },
  {
    id: 'u197',
    ar: 'قبل',
    tr: 'кабль',
    ru: 'до, раньше',
    kind: 'seed',
    tier: 'C',
    intro: 27,
    theme: 'Договорились',
    act: 30,
    nat: [],
    back: [],
    next: [38],
    enc: 1
  },
  {
    id: 'u198',
    ar: 'بعد',
    tr: 'баʿд',
    ru: 'после',
    kind: 'seed',
    tier: 'C',
    intro: 27,
    theme: 'Договорились',
    act: 30,
    nat: [],
    back: [],
    next: [38],
    enc: 1
  },
  {
    id: 'u199',
    ar: 'ألو',
    tr: 'алю́',
    ru: 'алло',
    kind: 'core',
    tier: 'B',
    intro: 28,
    theme: 'Алло',
    act: null,
    nat: [],
    back: [],
    next: [34, 40, 38],
    enc: 1
  },
  {
    id: 'u200',
    ar: 'من معي؟',
    tr: 'ман ма́ʿи?',
    ru: 'кто говорит? (кто со мной?)',
    kind: 'core',
    tier: 'B',
    intro: 28,
    theme: 'Алло',
    act: null,
    nat: [],
    back: [],
    next: [34, 40, 38],
    enc: 1
  },
  {
    id: 'u201',
    ar: 'لحظة من فضلك',
    tr: 'ла́хза мин фа́длик',
    ru: 'секундочку, пожалуйста',
    kind: 'core',
    tier: 'B',
    intro: 28,
    theme: 'Алло',
    act: null,
    nat: [],
    back: [],
    next: [34, 40, 38],
    enc: 1
  },
  {
    id: 'u202',
    ar: 'يجيب / لا يجيب',
    tr: 'юджи́б / ля юджи́б',
    ru: 'отвечает / не отвечает',
    kind: 'core',
    tier: 'B',
    intro: 28,
    theme: 'Алло',
    act: null,
    nat: [],
    back: [],
    next: [34, 40, 38],
    enc: 1
  },
  {
    id: 'u203',
    ar: 'رقم',
    tr: 'ракм',
    ru: 'номер',
    kind: 'seed',
    tier: 'C',
    intro: 28,
    theme: 'Алло',
    act: 30,
    nat: [],
    back: [],
    next: [38],
    enc: 1
  },
  {
    id: 'u204',
    ar: 'خطأ',
    tr: 'ха́таʼ',
    ru: 'ошибка',
    kind: 'seed',
    tier: 'C',
    intro: 28,
    theme: 'Алло',
    act: 29,
    nat: [],
    back: [],
    next: [37],
    enc: 1
  },
  {
    id: 'u205',
    ar: 'سامحني',
    tr: 'са́михни',
    ru: 'прости меня',
    kind: 'core',
    tier: 'B',
    intro: 29,
    theme: 'Прости',
    act: null,
    nat: [],
    back: [],
    next: [31, 35, 41],
    enc: 1
  },
  {
    id: 'u206',
    ar: 'نسيت',
    tr: 'наси́ту',
    ru: 'я забыл',
    kind: 'core',
    tier: 'B',
    intro: 29,
    theme: 'Прости',
    act: null,
    nat: [30],
    back: [],
    next: [31, 35],
    enc: 2
  },
  {
    id: 'u207',
    ar: 'فعلت',
    tr: 'фаʿа́льту',
    ru: 'я сделал',
    kind: 'core',
    tier: 'B',
    intro: 29,
    theme: 'Прости',
    act: null,
    nat: [],
    back: [],
    next: [31, 35, 41],
    enc: 1
  },
  {
    id: 'u208',
    ar: 'لا بأس',
    tr: 'ля баʼс',
    ru: 'ничего страшного',
    kind: 'core',
    tier: 'A',
    intro: 29,
    theme: 'Прости',
    act: null,
    nat: [],
    back: [],
    next: [32, 36, 42, 50, 37],
    enc: 1
  },
  {
    id: 'u209',
    ar: 'كسرت',
    tr: 'каса́рту',
    ru: 'я сломал',
    kind: 'seed',
    tier: 'C',
    intro: 29,
    theme: 'Прости',
    act: 30,
    nat: [],
    back: [],
    next: [38],
    enc: 1
  },
  {
    id: 'u210',
    ar: 'الحق معك',
    tr: 'аль-хакк ма́ʿак',
    ru: 'ты прав (правда с тобой)',
    kind: 'seed',
    tier: 'C',
    intro: 29,
    theme: 'Прости',
    act: 30,
    nat: [30],
    back: [],
    next: [],
    enc: 2
  },
  {
    id: 'u211',
    ar: 'كان',
    tr: 'ка́на',
    ru: 'был',
    kind: 'core',
    tier: 'A',
    intro: 30,
    theme: 'Кто был прав',
    act: null,
    nat: [],
    back: [],
    next: [31, 33, 37, 43, 51],
    enc: 1
  },
  {
    id: 'u212',
    ar: 'كانت',
    tr: 'ка́нат',
    ru: 'была',
    kind: 'core',
    tier: 'A',
    intro: 30,
    theme: 'Кто был прав',
    act: null,
    nat: [],
    back: [],
    next: [31, 33, 37, 43, 51],
    enc: 1
  },
  {
    id: 'u213',
    ar: 'أمس',
    tr: 'амс',
    ru: 'вчера',
    kind: 'core',
    tier: 'A',
    intro: 30,
    theme: 'Кто был прав',
    act: null,
    nat: [],
    back: [],
    next: [31, 33, 37, 43, 51],
    enc: 1
  },
  {
    id: 'u214',
    ar: 'صحيح',
    tr: 'сахи́х',
    ru: 'верно, правда',
    kind: 'core',
    tier: 'B',
    intro: 30,
    theme: 'Кто был прав',
    act: null,
    nat: [],
    back: [],
    next: [32, 36, 42],
    enc: 1
  },
  {
    id: 'u215',
    ar: 'كنت',
    tr: 'ку́нту',
    ru: 'я был',
    kind: 'seed',
    tier: 'C',
    intro: 30,
    theme: 'Кто был прав',
    act: 31,
    nat: [],
    back: [],
    next: [31],
    enc: 1
  },
  {
    id: 'u216',
    ar: 'زمان',
    tr: 'зама́н',
    ru: 'давно, прежде',
    kind: 'seed',
    tier: 'C',
    intro: 30,
    theme: 'Кто был прав',
    act: 31,
    nat: [],
    back: [],
    next: [31],
    enc: 1
  }
];
